import { format } from "date-fns";

export const createBookingsFormData = (
  selectfirstDate,
  setselectfirstDate,
  selectlastDate,
  setselectlastDate,
  disabledDates,
  toggleFirstDatePickerVisibility,
  isFirstDatePickerVisible,
  toggleLastDatePickerVisibility,
  isLastDatePickerVisible,
  handleDiscountChange,
  setFlatDiscount,
  calculateTotalAmount
) => [
  {
    id: 2,
    label: "Name",
    type: "text",
    placeholder: "Guest's Name",
    name: "customerName",
    required: true,
  },
  {
    id: 3,
    label: " Contact Number",
    // label: "Company Name / Address",
    type: "number",
    placeholder: "Company Name",
    name: "customerNumber",
    required: true,
  },
  {
    id: 4,
    // label: "Guest's Authentication",
    label: "Company Name / Address",
    type: "text",
    placeholder: "Contact Number",
    // name: "authentication",
    // values: ["NID", "Passport", "Driving Licence number"],
    required: false,
  },
  // {
  //   id: 4,
  //   // label: "Guest's authentication Number",
  //   label: "Guest's authentication Number",
  //   type: "text",
  //   placeholder: "Guest's authentication Number",
  //   name: "authenticationNumber",
  //   required: false,
  // },
  {
    id: 5,
    // label: "Person",
    label: "Host Name",
    type: "text",
    placeholder: "Host Name & Number",
    name: "person",
    required: false,
  },
  {
    id: 6,
    label: "Check in Date",
    type: "date",
    placeholder: "Select Check in Date",
    name: "firstDate",
    selectedDate: selectfirstDate,
    setselectedDate: setselectfirstDate,
    disabledDays: disabledDates,
    toggleDatePickerVisibility: toggleFirstDatePickerVisibility,
    isDatePickerVisible: isFirstDatePickerVisible,
    // required: true,
  },
  {
    id: 7,
    label: "Check Out Date",
    type: "date",
    placeholder: "Select Check Out Date",
    name: "lastDate",
    selectedDate: selectlastDate,
    setselectedDate: setselectlastDate,
    disabledDays: disabledDates,
    toggleDatePickerVisibility: toggleLastDatePickerVisibility,
    isDatePickerVisible: isLastDatePickerVisible,
    // required: true,
  },
  {
    id: 850,
    label: "Room Name",
    // type: "select",
    placeholder: "Room Name",
    name: "roomName",
    onChange: (e) => setRoomName(e.target.value),
    // required: true,
  },
  {
    id: 8,
    label: "Room Number",
    // type: "select",
    placeholder: "Room Number",
    name: "roomNumber",
    // required: true,
  },
  // {
  //   id: 10,
  //   label: `Discount`,
  //   // type: "number",
  //   placeholder: "Discount",
  //   name: "discount",
  //   onChange: (e) => handleDiscountChange(e),
  //   onflatchange: (e) => {
  //     setFlatDiscount(e.target.value);
  //   },
  //   required: false,
  // },
  {
    id: 120,
    label: "Select Payment Method",
    // type: "select",
    placeholder: "Select Payment Method",
    name: "paymentMethod",
    values: ["Cash", "Bkash", "Check", "City Bank", "Prime Bank"],
    required: false,
  },
  {
    id: 11,
    label: `Advance Amount (${calculateTotalAmount()} Tk)`,
    type: "number",
    placeholder: "Paid Amount",
    name: "paidAmount",
    required: false,
  },
  // {
  //   id: 12,
  //   label: "Referred By",
  //   type: "text",
  //   placeholder: "Referred By",
  //   name: "referredBy",
  //   required: false,
  // },
  {
    id: 12,
    label: "Additional Information",
    type: "text",
    placeholder: "Remarks",
    name: "remarks",
    required: false,
  },
];
